### PR TITLE
resolve UI and boundingbox/text highlighting issues

### LINKED ISSUE #462: text highlighting bugs
- [x] when selecting a syl/bounding box, the text in the bottom left should also turn red
- [x] when highlighting by neume and mousing over the text in the bottom right, the neume components will not be highlighted in red
- [x] when highlighting by staff and selecting a syllable, the associated bounding box will not turn red

### LINKED ISSUE #466: weird animation when resizing bounding boxes on diva view
when resizing bounding boxes while in diva view, the black rectangle will be redrawn around the original bbox size for a second before the both black boxes disappear and the resizing is successful and the bounding box is unselected. desired behaviour: same as in single page view. no second rectangle should appear, and the bounding box should remain selected after the resizing action

### LINKED ISSUE #467: Change icon for selecting syllable bounding box
Instead of having the following way of representing the editing of bounding boxes for syllables:

bbox_editing_old

We should use the standard:

bbox_editing_new

In addition, if grabbing any of the vertices, the user should be able to edit width and height at the same time.

### LINKED ISSUE #468: Fix responsiveness in non-standard browser width
Some browser widths make the File and Help menus to appear in strange zones of the page. 

menus

### LINKED ISSUE #469: text bounding box disappears while dragging
in diva view, if you click and drag a bounding box, then quickly click and drag it again before it can un-select and be re-selected, then it will sometimes disappear completely

### LINKED ISSUE #472: page updating not happening when in diva view
calling neonView.updateForCurrentPage() or await neonView.updateForCurrentPagePromise() doesn't update the page when in diva view mode. So when resizing and dragging bboxes/staves the page doesn't update in the dragEnded/resizeEnded method like they are suppose to. This is what is causing #466 and #469

### LINKED ISSUE #473: delete button does not work in grouping menu
when the grouping menu is displaying the delete button doesn't have an event listener and so doesn't work

### LINKED ISSUE #474: make sure that resizing points are above other elements in the svg
the resizing points don't always get rendered above elements in the svg, so sometimes when a boundingbox is selected, its resizing points are painted below another boundingbox, meaning that when you click on them you actually end up clicking on the other bounding box

### PR DESCRIPTION
**Pull request by jacob-hutnyk**
- resolves #462: changes to what gets highlighted and selected when clicking on or mousing over things, and added highlighting of text when selecting it's syllable
- resolves #468: change to burger menu view at a slightly smaller width
- resolves #472: change changePage() and updateForCurrentPage() functions so that they take an optional parameter as to whether to delay loading the verovio render. In the case of loading the page for the first time it should delay (on diva view specifically), but when doing editor actions it should not. This fixes #466 and fixes #469 
- resolves #467 by changing the aesthetic and functionality of resizing
- resolves #473 
- resolves #474

### CODE REVIEW

File: src/DivaView.js [hunk 1]
```diff
@@ -38,16 +38,18 @@ class DivaView {
   /**
    * Called when the visible page changes in the diva.js viewer.
    * @param {number | number[]} pageIndexes - The zero-index or -indexes of the page(s) visible.
+   * @param {boolean} delay - whether to delay the loading of the page. defaults to true
```
Comment (JRegimbal) [inline src/DivaView.js]: Since this is optional with a default value, the correct way to represent this with jsdoc would be `@param {boolean} [delay=true]`.

File: src/NeonView.js [hunk 2]
```diff
@@ -63,25 +63,27 @@ class NeonView {
...
       }
     }); */
-    this.core.initDb().then(() => { this.updateForCurrentPage(); });
+    this.core.initDb().then(() => { this.updateForCurrentPage(true); });
   }
 
   /**
    * Get the current page from the loaded view and then display the
    * most up to date SVG.
+   * @param {boolean} delay. whether or not to delay loading the page by 500ms. defaults to false
```
Comment (JRegimbal) [inline src/NeonView.js]: Correct should be `@param {boolean} [delay=false] - whether or not...`

Comment (JRegimbal) [reply src/NeonView.js]: Also is this 500 ms hard coded? If it is put in a variable somewhere, reference the variable instead of the value (which could change).

File: src/NeonView.js [hunk 3]
```diff
@@ -63,25 +63,27 @@ class NeonView {
...
-  updateForCurrentPage () {
+  updateForCurrentPage (delay = false) {
     let pageNo = this.view.getCurrentPage();
-    this.view.changePage(pageNo);
+    this.view.changePage(pageNo, delay);
   }
 
   /**
    * Same as updateForCurrentPage but returns a promise.
+   * @param {boolean} delay. whether or not to delay loading the page by 500ms. defaults to false
```
Comment (JRegimbal) [inline src/NeonView.js]: Same as above.

File: src/NeonView.js (hunk 2 above)
Comment (jacob-hutnyk) [reply src/NeonView.js]: it's not hard coded it refers to this.loadDelay in divaview.js

File: src/NeonView.js [hunk 4]
```diff
@@ -69,7 +69,7 @@ class NeonView {
   /**
    * Get the current page from the loaded view and then display the
    * most up to date SVG.
-   * @param {boolean} delay. whether or not to delay loading the page by 500ms. defaults to false
+   * @param {boolean} [delay=false]. whether or not to delay loading the page by 500ms. defaults to false
```
Comment (JRegimbal) [inline src/NeonView.js]: The period is not correct syntax. Change to `[delay=false] - whether`. Currently JSDoc would throw a warning and interpret the variable as being named `delay.`.

File: src/NeonView.js [hunk 5]
```diff
@@ -78,7 +78,7 @@ class NeonView {
 
   /**
    * Same as updateForCurrentPage but returns a promise.
-   * @param {boolean} delay. whether or not to delay loading the page by 500ms. defaults to false
+   * @param {boolean} [delay=false]. whether or not to delay loading the page by 500ms. defaults to false
```
Comment (JRegimbal) [inline src/NeonView.js]: Same as above.
